import { StyleSheet } from "react-native";

export const UserProfileStyle = StyleSheet.create({
  content: {
    display: "flex",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    backgroundColor: "rgb(109,49,158)",
  },
  view: {
    width: "80%",
  },
  cardTitle: {
    color: "rgb(134,68,162)",
  },
  cardButton: {
    margin: 5,
    marginLeft: 0,
    marginRight: 0,
  },
  textStyle: {
    margin: 5,
    marginLeft: 0,
    marginRight: 0,
    color: "rgb(103,80,164)",
    textAlign: "center",
  },
  text: {
    margin: 5,
    marginLeft: 0,
    marginRight: 0,
    color: "#ffffff",
    textAlign: "center",
  },
  textInput: {
    backgroundColor: "transparent",
  },
  surface: {
    padding: 8,
    height: 80,
    width: 80,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    borderWidth: 1,
    borderColor: "#434343",
  },
  container: {
    flex: 0,
    backgroundColor: "-webkit-linear-gradient(305deg, #4f0854,#7339ac,#a75892)",
    alignItems: "center",
    justifyContent: "center",
    width: "90%",
    height: null,
    color: "#ffffff",
    flexDirection: "row",
    flexWrap: "wrap",
  },
  heading: {
    flex: 0,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    height: null,
    color: "#ffffff",
    flexDirection: "column",
    flexWrap: "wrap",
  },
  containerColumn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
    height: null,
    color: "#ffffff",
    flexDirection: "column",
    flexWrap: "nowrap",
    alignSelf: "stretch",
  },
  containerHeading: {
    alignItems: "center",
    justifyContent: "flex-start",
    width: "85%",
    height: null,
    color: "#ffffff",
    flexDirection: "row",
    flexWrap: "nowrap",
    backgroundColor: "#DDBAFF",
    margin: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#434343",
  },
  containerDescription: {
    alignItems: "center",
    justifyContent: "center",
    width: "85%",
    height: null,
    color: "#ffffff",
    flexDirection: "row",
    flexWrap: "nowrap",
    backgroundColor: "rgb(109,49,158)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FFF",
  },
  socialMedia: {
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "85%",
    height: null,
    color: "#ffffff",
    flexDirection: "row",
    flexWrap: "nowrap",
    backgroundColor: "rgb(109,49,158)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FFF",
    marginTop: 5
  },
  socialMediaTags: {
    flex: 0,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    height: null,
    color: "#ffffff",
    flexDirection: "column",
    flexWrap: "wrap",
    margin: 7,
    fontStyle: "italic",
  },
  description: {
    flex: 0,
    alignItems: "center",
    justifyContent: "center",
    height: null,
    color: "#ffffff",
    flexDirection: "column",
    flexWrap: "wrap",
    margin: 7,
    fontStyle: "italic",
  },
  containerRow: {
    flex: 0,
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
    height: null,
    color: "#ffffff",
    flexDirection: "row",
    flexWrap: "nowrap",
    alignSelf: "stretch",
    marginLeft: 30,
    margin: 15,
  },
  avatar: {
    marginLeft: -10,
  },
  image: {
    flex: 1,
    justifyContent: "center",
  },
  name: {
    color: "#000000",
    fontSize: 20,
    fontWeight: "500",
    marginLeft: 10,
  },
  title: {
    color: "#434343",
    fontSize: 15,
    fontWeight: "500",
    marginLeft: 10,
  },
  badge: {
    color: "#434343",
    fontSize: 12,
    fontWeight: "800",
    marginLeft: 20,
    backgroundColor: "orange",
    borderWidth: 1,
    borderColor: "#434343",
    alignSelf: "center",
  },
  activityBadge: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
    marginLeft: 20,
    backgroundColor: "#4dad32",
    borderWidth: 1,
    borderColor: "#434343",
    alignSelf: "center",
  },
  piechart:{
    borderWidth: 3,
    borderColor: "#FFF",
    alignSelf: "center",
    borderRadius: 120,
  },
  javadot:{
    height: 25,
    width: 25,
    backgroundColor: "#046393",
    borderWidth: 3,
    borderColor: "#FFF",
  },
  jsdot:{
    height: 25,
    width: 25,
    backgroundColor: "#f9e40f",
    borderWidth: 3,
    borderColor: "#FFF",
  },
  phpdot:{
    height: 25,
    width: 25,
    backgroundColor: "#f76040",
    borderWidth: 3,
    borderColor: "#FFF",
  },
  piechartColumn: {
    flex: 0,
    alignItems: "center",
    justifyContent: "center",
    width: "20%",
    height: null,
    color: "#ffffff",
    flexDirection: "column",
    flexWrap: "nowrap",
    alignSelf: "stretch",
  },

  list: {
    flex: 1,
    marginTop:20,
  },

  timeline: {
    flex: 1,
    width: '100%',
    padding: 20,
		paddingTop:20,
		backgroundColor:'white'
  },
});
